version: dev-{build}
build_script:
- cmd: >-
    @echo off
    echo %APPVEYOR_REPO_COMMIT_MESSAGE% | find /I "release" > nul
    if %errorlevel%==0 (
        echo Make the release build
        build.cmd
    ) else (
        echo Make the regular dev build
        build.cmd --version-suffix %APPVEYOR_BUILD_VERSION%
    )
test: off
artifacts:
- path: artifacts\*.nupkg
  name: NuGetPackages